### ISSUE TITLE
Logo for CamTools

### ISSUE THREAD

**Issue by hafizahmmed** [koenidv/CamTools#1]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![camtools-01](https://user-images.githubusercontent.com/38810169/40575803-63dfeaec-610d-11e8-8d5e-42c091245e40.jpg)

**Comment by koenidv** [comment]
Sorry, but I don't think that this project is ready for a logo yet.
But thank you for the effort!
